export const apiRoutes = {
  health: "/api/v1/health",
  register: "/api/v1/auth/register",
  login: "/api/v1/auth/login",
  refresh: "/api/v1/auth/refresh",
  me: "/api/v1/me",
  meAvatar: "/api/v1/me/avatar",
  meRequests: "/api/v1/me/requests",
  meTips: "/api/v1/me/tips",
  meComplimentaryCredits: "/api/v1/me/complimentary-credits",
  redeemComplimentaryCode: "/api/v1/me/complimentary-credits/redeem",
  djs: "/api/v1/djs",
  djProfile: "/api/v1/djs/profile",
  djEvents: "/api/v1/djs/events",
  venues: "/api/v1/venues",
  venuePlacesSearch: "/api/v1/venues/places/search",
  sessionsNearby: "/api/v1/sessions/nearby",
  currentDjSession: "/api/v1/dj/sessions/current",
  resetCurrentDjQueue: "/api/v1/dj/sessions/current/queue/reset",
  songsSearch: "/api/v1/songs/search",
} as const;

export const apiRouteBuilders = {
  sessionRequests: (sessionId: number | string) => `/api/v1/sessions/${sessionId}/requests`,
  sessionPlayedRequests: (sessionId: number | string) => `/api/v1/sessions/${sessionId}/requests/played`,
  sessionExpiredRequests: (sessionId: number | string) => `/api/v1/sessions/${sessionId}/requests/expired`,
  createSessionRequest: (sessionId: number | string) => `/api/v1/sessions/${sessionId}/requests`,
  request: (requestId: number | string) => `/api/v1/requests/${requestId}`,
  contributeToRequest: (requestId: number | string) => `/api/v1/requests/${requestId}/contribute`,
  undoRequest: (requestId: number | string) => `/api/v1/requests/${requestId}/undo`,
    confirmRequest: (requestId: number | string) => `/api/v1/dj/requests/${requestId}/confirm`,
  markRequestPlayed: (requestId: number | string) => `/api/v1/dj/requests/${requestId}/played`,
  currentDjRequests: "/api/v1/dj/requests/current",
  currentDjPlayedRequests: "/api/v1/dj/requests/played",
  currentDjExpiredRequests: "/api/v1/dj/requests/expired",
  djEarnings: "/api/v1/dj/earnings",
  djPayments: "/api/v1/dj/payments",
  djWithdraw: "/api/v1/dj/payouts/withdraw",
  currentDjTips: "/api/v1/dj/tips/current",
  currentDjThankedTips: "/api/v1/dj/tips/thanked",
  djEvent: (eventId: number | string) => `/api/v1/djs/events/${eventId}`,
  djEventExtend: (eventId: number | string) => `/api/v1/djs/events/${eventId}/extend`,
  djEventEnd: (eventId: number | string) => `/api/v1/djs/events/${eventId}/end`,
  djEventFlyer: (eventId: number | string) => `/api/v1/djs/events/${eventId}/flyer`,
  djEventComplimentaryCodes: (eventId: number | string) =>
    `/api/v1/djs/events/${eventId}/complimentary-codes`,
  djEventsBySlug: (slug: string) => `/api/v1/djs/${slug}/events`,
  sessionTips: (sessionId: number | string) => `/api/v1/sessions/${sessionId}/tips`,
  thankTip: (tipId: number | string) => `/api/v1/dj/tips/${tipId}/thank`,
  djListenerProfile: (userId: number | string) => `/api/v1/dj/listeners/${userId}`,
} as const;
